package pack;

import java.awt.Color;
import pack.Afisare;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class Initiere extends javax.swing.JFrame {

    public Afisare afis;
    public String text = "";
    private char personSex = 'S';

    public void setPersonSex(char c) {
        personSex = c;
    }

    public Initiere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitlu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comp1 = new javax.swing.JTextField();
        comp2 = new javax.swing.JTextField();
        comp3 = new javax.swing.JTextField();
        comp4 = new javax.swing.JTextField();
        comp5 = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        numeCompetent = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textTitlu.setFont(new java.awt.Font("Palace Script MT", 3, 48)); // NOI18N
        textTitlu.setForeground(new java.awt.Color(255, 255, 255));
        textTitlu.setText("Adaugati Competentele ");
        textTitlu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textTitluAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(textTitlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 360, 68));

        jLabel1.setFont(new java.awt.Font("Kunstler Script", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        jLabel2.setFont(new java.awt.Font("Kunstler Script", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("C2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, -1));

        jLabel3.setFont(new java.awt.Font("Kunstler Script", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C3:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, -1));

        jLabel4.setFont(new java.awt.Font("Kunstler Script", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("C4:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        jLabel5.setFont(new java.awt.Font("Kunstler Script", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("C5:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, -1));

        comp1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comp1.setForeground(new java.awt.Color(255, 255, 255));
        comp1.setBackground(new Color(0,0,0,0));
        getContentPane().add(comp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, -1));

        comp2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comp2.setForeground(new java.awt.Color(255, 255, 255));
        comp2.setBackground(new Color(0,0,0,0));
        getContentPane().add(comp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 240, -1));

        comp3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comp3.setForeground(new java.awt.Color(255, 255, 255));
        comp3.setBackground(new Color(0,0,0,0));
        getContentPane().add(comp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, -1));

        comp4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comp4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(comp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 240, -1));
        comp4.setBackground(new Color(0,0,0,0));

        comp5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comp5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(comp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, -1));
        comp5.setBackground(new Color(0,0,0,0));

        jB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/chekmark.png"))); // NOI18N
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 92, 41));
        jB1.setBackground(new Color(0,0,0,0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Light_Close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 91, -1));
        jButton2.setBackground(new Color(0,0,0,0));

        numeCompetent.setFont(new java.awt.Font("Palace Script MT", 3, 48)); // NOI18N
        numeCompetent.setForeground(new java.awt.Color(255, 255, 255));
        numeCompetent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeCompetent.setText("Nume");
        getContentPane().add(numeCompetent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 56));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/source.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/60389c4e3fa21cd20413ca8c2bcae341.gif"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 400, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeTitle(String n) {
        numeCompetent.setText(n);
    }

    public String getText() {
        return text;
    }

    private void clear() {
        comp1.setText("");
        comp2.setText("");
        comp3.setText("");
        comp4.setText("");
        comp5.setText("");
        text="";
    }

    private void setareTextTransfer() {
        String s1 = comp1.getText();
        String s2 = comp2.getText();
        String s3 = comp3.getText();
        String s4 = comp4.getText();
        String s5 = comp5.getText();
        afis.adaugaC(s1, s2, s3, s4, s5);
        text = afis.toString();
    }
    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed

        if (personSex == 'M') {
            setareTextTransfer();
            afis.setTabel(text);
        } else {
            setareTextTransfer();

            afis.setTabelF(text);
        }
        clear();
        afis.j.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jB1ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textTitluAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textTitluAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitluAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Initiere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comp1;
    private javax.swing.JTextField comp2;
    private javax.swing.JTextField comp3;
    private javax.swing.JTextField comp4;
    private javax.swing.JTextField comp5;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel numeCompetent;
    private javax.swing.JLabel textTitlu;
    // End of variables declaration//GEN-END:variables

}
